
name: Swift Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest

    strategy:
      matrix:
        xcode-version: ['16.0']
        ios-version: ['18.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - name: Build and Test
        env:
          GIDClientID: ${{ secrets.GIDCLIENTID }}
        run: |
          xcodebuild clean build test \
          -scheme AdRevenueWatch \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=${{ matrix.ios-version }}' \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO
